
version: '3'

services:
  nodejs:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    command: node ./__sapper__/build
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - sessions:/data/sessions

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network

volumes:
  sessions:

networks:
  app-network:
    driver: bridge
