version: '3'
services:
  svelte:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - API_URL
    env_file:
      - ./.env
    command: node ./__sapper__/build
    restart: unless-stopped
    ports:
      - 80:3000
    volumes:
      - sessions:/data/sessions

volumes:
  sessions: